"""del link

Revision ID: 1dd03c1a4278
Revises: f806a74e71b8
Create Date: 2023-12-03 00:29:37.737967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dd03c1a4278'
down_revision = 'f806a74e71b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('link')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
