"""added created column

Revision ID: e0f4c45633b2
Revises: 1dd03c1a4278
Create Date: 2023-12-08 23:44:19.389185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0f4c45633b2'
down_revision = '1dd03c1a4278'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.drop_column('cost')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('created')

    # ### end Alembic commands ###
