"""initial migrate

Revision ID: f806a74e71b8
Revises: 
Create Date: 2023-12-03 00:02:34.000386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f806a74e71b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('show_date', sa.DateTime(), nullable=True),
    sa.Column('tickets', sa.String(), nullable=True),
    sa.Column('cost', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    # ### end Alembic commands ###
