name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: leerobertdyer/vavl2024:v1.0.1

    - name: Trigger deployment on Render
      run: |
        curl -X POST -d ''  https://api.render.com/deploy/srv-co96mfq0si5c73978c90?key=LiTbz4pPaLg
